# Generated by Django 3.2.8 on 2021-10-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeVisited_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(max_length=30)),
                ('trip_start', models.DateTimeField(verbose_name='The start of trip')),
                ('trip_end', models.DateTimeField(verbose_name='The end of trip')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VisitHistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateTimeField(verbose_name='The date of visit')),
                ('place_visited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_diary.placevisited')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_diary.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_shooting', models.DateTimeField(verbose_name='date of shooting')),
                ('file_name', models.CharField(max_length=100)),
                ('importance', models.IntegerField()),
                ('placesVisited_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_diary.placevisited')),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_diary.trip')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip_diary.user')),
            ],
        ),
    ]
