# Generated by Django 3.2 on 2021-10-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_diary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceVisited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start', models.DateTimeField(verbose_name='The start of trip')),
                ('end', models.DateTimeField(verbose_name='The end of trip')),
            ],
        ),
        migrations.CreateModel(
            name='VisitHistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.IntegerField()),
                ('place_visited', models.IntegerField()),
                ('date_of_visit', models.DateTimeField(verbose_name='The date of visit')),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='places_visited',
            field=models.IntegerField(),
        ),
    ]
